###

GET http://localhost:3000/usuario

###

POST  http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "João",
    "senha": "1231"
}

###

PUT  http://localhost:3000/usuario/3
Content-Type: application/json

{
    "nome": "Jonas",
    "senha": "6767"
}